# -*- coding: utf-8 -*-
"""Fintech_Mainscreen_Stock_Screnner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p4qweogMz-D7HYSMVMgYHeMfLXlGpSQK
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly
import requests
from bs4 import BeautifulSoup

class Price_Getter:
    def __init__(self, ticker: list or np.ndarray or pd.Series,
                 data_source = 'yahoo', data = 'live_tick'):
        self.ticker = ticker
        self.data_source = data_source
        self.data = data

    def yahoo_live_tick(self):
        while True:
            [self.yahoo_soup(ticker) for ticker in self.ticker]
            break
            

    def yahoo_soup(self, ticker):
        url = 'https://ca.finance.yahoo.com/quote/' + \
                ticker + '?p=' + ticker + '&.tsrc=fin-srch'
        soup = BeautifulSoup(requests.get(url).text, 'html.parser')
        
        price = soup.find('div', {'class': 'D(ib) Mend(20px)'}).\
                find_all('span')[0].text
        price_change = soup.find('div', {'class': 'D(ib) Mend(20px)'}).\
                find_all('span')[1].text
        print('Ticker: {}\n Price: {}\n Price_Change: {}'.format(ticker,
                                                                 price,
                                                                 price_change))


